server:
  port: 443
  ssl:
    key-store: /home/tincher/keystore/tincher_de.p7s
logging:
  file: /home/tincher/log/log.txt

---
spring:
  profiles: dev
server:
  port: 8443
  ssl:
    key-store: src/main/resources/keystore.p12
logging:
  file: C:/Users/Joel/Desktop/log.txt