server:
  port: 443
  ssl:
    key-store: /home/tincher/keystore/tincher_de.p12
logging:
  file: /home/tincher/log/log.txt
spring:
  datasource: 
    username: root
    password: qazesd

---
spring:
  profiles: dev
  datasource:
    username: tinch
    password: tinch
server:
  port: 8443
  ssl:
    key-store: src/main/resources/keystore.p12
logging:
  file: C:/Users/Joel/Desktop/log.txt